### ISSUE TITLE
Cannot install for python version

### ISSUE THREAD

**Issue by joneshf** [bodil/pulp#1]
I went to try and install this but ran into a python version error:

```
➜  ~  _ npm i -g pulp
[sudo] password for joneshf: 

> gaze@0.6.4 install /usr/lib/node_modules/pulp/node_modules/gaze
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: Python executable "python" is v3.4.1, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:108:14)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:97:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:646:7)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at maybeClose (child_process.js:756:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:823:5)
gyp ERR! System Linux 3.16.3-1-ARCH
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/pulp/node_modules/gaze
gyp ERR! node -v v0.10.32
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm ERR! Linux 3.16.3-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "i" "-g" "pulp"
npm ERR! node v0.10.32
npm ERR! npm  v2.1.0
npm ERR! code ELIFECYCLE

npm ERR! gaze@0.6.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gaze@0.6.4 install script.
npm ERR! This is most likely a problem with the gaze package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls gaze
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/joneshf/npm-debug.log
```

Looks like this is known: https://github.com/shama/gaze/issues/102 and apparently versions before `0.6.x` don't have this problem.

Can the version go down a minor? Or can a different watch tool be used?

**Comment by bodil** [comment]
Ugh, Python versions...

I'd almost go so far as to suggest an npm installation unable to invoke gyp is missing a fundamental dependency (python2) which you really should have installed if npm is to work reliably at all, but I'd be willing to accept a PR with a `gaze` version that builds for you. Uninstalling python2 isn't really something I'm able to do without breaking my own OS installation, so I'd have to rely on you to test if it builds or not.

Unless something new has appeared recently, `gaze` seems to be the only available watch package that works satisfactorily, so replacing it is probably not a good idea.

**Comment by joneshf** [comment]
I have py2 installed, it's just not the default for arch linux.

**Comment by bodil** [comment]
Odd, I never had a problem with this when running Arch. It should just find the `python2` command and work, iirc.

Anyway, I just ran into more or less the same problem on my Windows machine, and have a version built with gaze 0.5.1 that seems to work fine, and doesn't require gyp to build. I'll commit a fix once I'm sure I haven't broken anything.

**Comment by peterjoel** [comment]
I still get this error on Windows, while installing the latest version of pulp.

```
    $ npm install -g pulp
    \
    > utf-8-validate@1.2.1 install C:\Users\Peter\AppData\Roaming\npm\node_modules\pulp\node_modules\webpack-dev-server\node_modules\socket.io\node_modules\engine.i
    o\node_modules\ws\node_modules\utf-8-validate
    > node-gyp rebuild


    C:\Users\Peter\AppData\Roaming\npm\node_modules\pulp\node_modules\webpack-dev-server\node_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\
    utf-8-validate>if not defined npm_config_node_gyp (node "c:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js"
     rebuild )  else (node  rebuild )
    gyp ERR! configure error
    gyp ERR! stack Error: Python executable "true" is v, which is not supported by gyp.
    gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
    gyp ERR! stack     at failPythonVersion (c:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:121:14)
    gyp ERR! stack     at c:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:110:9
    gyp ERR! stack     at ChildProcess.exithandler (child_process.js:194:7)
    gyp ERR! stack     at emitTwo (events.js:87:13)
    gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
    gyp ERR! stack     at maybeClose (internal/child_process.js:817:16)
    gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:319:11)
    gyp ERR! stack     at emitOne (events.js:77:13)
    gyp ERR! stack     at Socket.emit (events.js:169:7)
    gyp ERR! stack     at Pipe._onclose (net.js:469:12)
    gyp ERR! System Windows_NT 6.3.9600
    gyp ERR! command "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
    gyp ERR! cwd C:\Users\Peter\AppData\Roaming\npm\node_modules\pulp\node_modules\webpack-dev-server\node_modules\socket.io\node_modules\engine.io\node_modules\ws\
    node_modules\utf-8-validate
    gyp ERR! node -v v4.1.1
    gyp ERR! node-gyp -v v3.0.3
    gyp ERR! not ok
```
